[build]
  functions = "netlify/functions"
  publish = "."

[[redirects]]
  from = "/api/posts/*/comments"
  to = "/.netlify/functions/comments?postId=:splat"
  status = 200

[[redirects]]
  from = "/api/posts/*/like"
  to = "/.netlify/functions/like?postId=:splat"
  status = 200

[[redirects]]
  from = "/api/posts/*/feel"
  to = "/.netlify/functions/feel?postId=:splat"
  status = 200

[[redirects]]
  from = "/api/posts"
  to = "/.netlify/functions/posts"
  status = 200
