[build]
  functions = "netlify/functions"
  publish = "."

[[redirects]]
  from = "/api/comments"
  to = "/.netlify/functions/comments"
  status = 200

[[redirects]]
  from = "/api/like"
  to = "/.netlify/functions/like"
  status = 200

[[redirects]]
  from = "/api/feel"
  to = "/.netlify/functions/feel"
  status = 200

[[redirects]]
  from = "/api/posts"
  to = "/.netlify/functions/posts"
  status = 200
